### load summary statistics RData file generated by genomicSEM
load("CD_sumstats.RData")

### split the summary statistics SNPs into smaller sets so that they can be processed faster (this one splits into sets of 6000)
split_sumstats <- split(CD_sumstats, (as.numeric(rownames(CD_sumstats))-1) %/% 6000)
### save each data frame as its own text file
### you can delete these files after you're done with the analyses
lapply(names(split_sumstats), function(x){write.table(split_sumstats[[x]], 
                                                      file = paste("./split_sumstats/split_sumstats2/sumstats", x,".txt", sep = ""), 
                                                      quote = FALSE, row.names=FALSE)})


### determine number of SNP sets and then save to a file
num_SNP_sets <- length(split_sumstats)
write.table(num_SNP_sets, file="num_SNP_sets2.txt", row.names=FALSE, col.names=FALSE, quote=FALSE)
